# conf/model/deepseek-vl-7b-chat.yaml
name: llava-one-vision_7b
class_path: model.LLaVAOneVision
model_size: 7B
test_mode: false
model_path: '/home2/ys_zheng/HugginfaceDownloader/llava-onevision-qwen2-7b-ov'
batch_size: 1