# conf/model/qwen25vl_7b.yaml
name: qwen25vl_7b
class_path: model.LoRAInferenceModel
model_size: 7B
test_mode: false
model_path: '/home/Qwen2.5-7B'
lora_checkpoint: '/home/checkpoint-3000_Qwen25Lora'
batch_size: 8