# conf/model/qwen25vl_7b.yaml
name: qwensftBoth
class_path: model.LoRAInferenceModel
model_size: 7B
test_mode: false
model_path: '/home2/ys_zheng/HugginfaceDownloader/Qwen2.5-VL-7B-Instruct'
batch_size: 8
lora_checkpoint: '/home2/ys_zheng/sft/output_orin_and_location/v3-20250505-152340/checkpoint-2600'

