# conf/model/qwen25vl_7b.yaml
name: qwen25vl_3b
class_path: model.InferenceModel
model_size: 7B
test_mode: false
model_path: '/home2/ys_zheng/HugginfaceDownloader/Qwen2.5-VL-3B-Instruct'
batch_size: 8
